name: Run appleblog Daily 

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1"
  # push:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"
      RUN_ENV: ${{ inputs.run_env || 'production' }} # within ['production', 'development']
      POWER: ${{ inputs.power || 16 }}
    steps:
      # ============================================
      # TODO [√] 检查工作分支及 Workflows 运行环境
      # ============================================
      - name: Checkout
        uses: actions/checkout@v4

      # ============================================
      # TODO [√] 创建 Python3.6+ 编译环境
      # ============================================
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # ============================================
      # TODO [√] 安装 Project 第三方依赖
      # ============================================
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ============================================
      # TODO [√] 测试 Scaffold 脚手架指令
      # ============================================
      - name: Run daily arxiv
        run: |
          python src/github/daily_github_appleblog.py run --env=${{ env.RUN_ENV }} --power=${{ env.POWER }}
        env:
          repo: ${{github.repository}}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SILICON_TOKEN: ${{ secrets.SILICON_TOKEN }}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}

      # ============================================
      # TODO [√] 更新仓库数据
      # ============================================
      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: Push done work
        run: |
          git add --all
          git commit -m "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${{ env.TZ }}"
          git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ============================================
      # TODO [√] 更新 vercel
      # ============================================
      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REQUIREMENTS: requirements-mkdocs.txt
